###CREATE USER (sign-up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Fourth test",
  "email": "Fourthtest@test.com",
  "password": "password",
  "password_confirmation": "password"
}