
# @jwt_sam = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE2NzUyMTl9.FKOR93S3GVR7COF2aYcIvKlZgLhEl7CsVht-Zv-yR7c
# @jwt_aaron = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTE1OTA4Nzh9.L5ZQbLatJiPCelfT5jd8-TV9ySpuI4McU92w6LfxfsU

###CREATE USER (sign-up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Hermione Granger",
  "email": "Hermione@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###SESSIONS CREATE
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Sam@example.com",
  "password": "password"
}

                            # EXPERIENCE #
###INDEX EXPERIENCE 
GET http://localhost:3000/experiences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE2NzUyMTl9.FKOR93S3GVR7COF2aYcIvKlZgLhEl7CsVht-Zv-yR7c
Content-Type: application/json

###CREATE EXPERIENCE 
POST http://localhost:3000/experiences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE2NzUyMTl9.FKOR93S3GVR7COF2aYcIvKlZgLhEl7CsVht-Zv-yR7c
Content-Type: application/json

{
  "category": "Skill",
  "description": "hat making"
  }

###SHOW EXPERIENCE 
GET http://localhost:3000/experiences/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE2NzUyMTl9.FKOR93S3GVR7COF2aYcIvKlZgLhEl7CsVht-Zv-yR7c
Content-Type: application/json

###UPDATE EXPERIENCE 
PATCH http://localhost:3000/experiences/14
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTE1OTA4Nzh9.L5ZQbLatJiPCelfT5jd8-TV9ySpuI4McU92w6LfxfsU
Content-Type: application/json

{
  "description": "Makes great hot chocolate"
}

                              # TRAINING #
###INDEX TRAINING 
GET http://localhost:3000/trainings
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE2NzUyMTl9.FKOR93S3GVR7COF2aYcIvKlZgLhEl7CsVht-Zv-yR7c
Content-Type: application/json

###CREATE TRAINING 
POST http://localhost:3000/trainings
Content-Type: application/json

{
  "user_id": 1,
  "category": "Education",
  "org_or_institution": "Actualize Coding Bootcamp",
  "description": "Full-stack engineering bootcamp that teaches you to teach yourself.",
  "dates": "Jan - May 2022",
  "degree_or_cert": "certificate",
  "location": "Remote ",
  "misc": "tech education"
}

###SHOW TRAINING 
GET http://localhost:3000/trainings/4
Content-Type: application/json

###UPDATE TRAINING
PATCH http://localhost:3000/trainings/3
Content-Type: application/json

{
  "degree_or_cert": "Degree"
}